### ISSUE TITLE
New folders and ccb-files are created in wrong location

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#102]
If using the plus sign in the lower left corner or using the File > New > Folder/File commands the folders and files are not created in the root directory. (Instead they are added to the ccbResources folder, at least in the default project)

**Comment by jtwigg** [comment]
Fixed for the popup menu on the Resource Outline view as well as the main Menu.

**Comment by vlidholt** [comment]
I'm still having issues with this. I think it is placing items in the last used directory, but definitely not always in the root directory.

**Comment by vlidholt** [comment]
Need to verify if this is working or not in all cases.

**Comment by NickyWeber** [comment]
I played around for a while and was not able to reproduce this behaviour. The file was correctly created in the root folder if nothing was selected. File was created in folder when one was selected.

**Comment by vlidholt** [comment]
Ok, I see my confusion now. It creates the file in the selected folder, I just assumed it would show up on the root level. This may be a correct behavior. I'm closing this,
