### ISSUE TITLE
CCBFile Anchorpoint Issue

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#1298]
Surprised this has never come up before so perhaps I'm just using it wrong however if I compare SpriteBuilder Editor vs Simulator they should match.

Anchor Point in CCSprite (File) 0.5,0.5 - I would also expect in editor to be in the middle of the crosshair. In Simulator it looks like 0.5,0.5.

![anchorccbfile-0 5-0 5](https://cloud.githubusercontent.com/assets/928115/5800485/016a6892-9fd7-11e4-9ebb-f1c5ba8e6b95.png)

Anchor 0.0,0.0

![anchorccbfile-0 0-0 0](https://cloud.githubusercontent.com/assets/928115/5800495/12a910b8-9fd7-11e4-9068-109f0040f8c9.png)

**Comment by cocojoe** [comment]
So think this is due to my CCBFile having 0 content Size for some reason.

**Comment by dionlarson** [comment]
This seems to be because CCBs with a base class of CCSprite do not write their content size to the file -- it's based on the sprite frame. When the CCB is added into another CCB, the content size is assumed to be zero instead of using the sprite frame's size.

**Comment by NickyWeber** [comment]
@dionlarson Exactly. We also figured this out but didn't comment here any further.

**Comment by Shahidwerplay** [comment]
This issue is fixed. 

Mac OS 10.10.0
SB Version 1.4.9.
XCode 6.2

**Comment by mtan3** [comment]
I have the above versions, but I still cannot change the CCB content size. Is there any other way to go about it?
