### ISSUE TITLE
Objects become invisible at higher zoom magnifications outside the current scene borders

### ISSUE THREAD

**Issue by tangogrowler** [spritebuilder/SpriteBuilder#1435]
Happens for levels that are larger than the scene size and objects which are outside the scene borders. These objects are visible until a certain zoom magnification is reached via the Cmd+. Current SB Version: 1.4.7 / SB Revision: 10891b8. OSX is 10.10.2

**Comment by sana20** [comment]
This issue is fixed.

Mac OS X: 10.10.1 and 10.10.5
XCode: 6.2
SB version: 1.4.7
SBAndroid version: sbandroid-starter-9f673a75 and sbandroid-indie-9f673a75

**Comment by tangogrowler** [comment]
Sorry, can you clarify please? Does that mean you've just fixed it - for the next release perhaps. Or it was already fixed?

**Comment by sana20** [comment]
@tangogrowler i tried this on my SB version: 1.4.7. and this issue was not occurring so i commented on this issue that it is fixed.

**Comment by tangogrowler** [comment]
Issue NOT fixed then, since it happens consistently on my up-to-date SB1.4.7 Revision: 10891b8

Node in question is a LAYER. Contents size (100% , 812pts) 

I can supply screenshots if that would help

**Comment by tangogrowler** [comment]
![screenshot 2015-03-22 12 30 37](https://cloud.githubusercontent.com/assets/9048033/6769355/b4636474-d08f-11e4-87b2-2b2f3ef03e6e.png)
![screenshot 2015-03-22 12 31 08](https://cloud.githubusercontent.com/assets/9048033/6769356/b4657462-d08f-11e4-9e86-8b027aa1203e.png)

**Comment by sana20** [comment]
i have made this video with the properties you just told content size 100% and 812 points and on layer it is. https://drive.google.com/file/d/0B23s5OMd3iivdGc3R1E0dlkxMjA/view?usp=sharing 
I am not having this issue. Please go through the video

**Comment by tangogrowler** [comment]
Ok, my video is here...
https://www.dropbox.com/sh/4yxdlsxll33wutk/AACge_jZvnlHpxq7x8QmCv3ua?dl=0

It covers this issue and CCB SFN drag & drop issue #1434. Maybe both are related to CCPhysicsNode..?
