### ISSUE TITLE
Imported CCB file property not saved.

### ISSUE THREAD

**Issue by cosminpahomi** [spritebuilder/SpriteBuilder#171]
If I import a CCB into a larger CCB (let's say main scene) and change a custom property for the imported CCB, the property will not be saved and the default one is the one from the original file that I've imported.

**Comment by vlidholt** [comment]
This bug needs verification and/or fix.

**Comment by NickyWeber** [comment]
Hi @cosminpahomi,
how did you import the ccb file? I tried copy pasting a custom class node with a custom property and that worked correctly.
- Nicky

**Comment by NickyWeber** [comment]
I can reproduce this now. Fix is on the way.

**Comment by NickyWeber** [comment]
Fixed: Pull request is on the way.

**Comment by catphive** [comment]
I'm still seeing this problem in spritebuilder 1.0.6 (2a1e3712de), which is the current one in the app store.

Possibly a regression?

Here's the pull request the was supposed to have fixed it.

https://github.com/spritebuilder/SpriteBuilder/pull/300
