### ISSUE TITLE
Hide field in timeline and visible field in the property inspector are not related.

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#492]
1. Launch application.
2. Drag drop CCTextfield on the Mainscreen.ccb file.
3. Select CCTextfield.
4. Un-check visible field in the property inspector..
   
   -- Result: Hide icon on the timeline doesn't change.
      This happened 3/3 times.

![screen shot 2014-05-14 at 8 12 41 pm](https://cloud.githubusercontent.com/assets/7450007/2973319/a9972b92-db7c-11e3-88f0-f66466e71023.png)

Found on SpriteBuilder-1.1.0-beta.0.zip

Mac 10.9.2.
2.4 GHz Intel Core i7

**Comment by khanbhai89** [comment]
This issue is still occurring on SpriteBuilder-1.3.0-rc.1.zip on Mac OS X: 10.9.5. and XCode: 6.0.

**Comment by khanbhai89** [comment]
This issue is still occurring on SpriteBuilder-1.3.4-rc.1 on:

Mac OS X: 10.10
XCode: 6.0.

**Comment by cocojoe** [comment]
Are they supposed to be related? As no node type behaves like this, not just `CCTextField`

The timeline visibility icon I thought was more of an editing feature so I can quickly hide layers to work on other layers etc 
The visibility in property panel I would expect if unticked to actually change the visibility property of the node.

**Comment by Kanoot** [comment]
This issue is fixed as visibility option of timeline and property inspector works exactly same way.

Build: SpriteBuilder-1.3.6.rc.1

Mac OS X: 10.9.5.
XCode: 6.0.

**Comment by NoorFatima** [comment]
This issue is still not fixed.

Mac OS X: 10.9.5
XCode: 6.1
SB Version: 2.0.0
SB Revision: 4fd68fb2bf

**Comment by cocojoe** [comment]
Why is this still being commented on, it's closed.

The eye icon in the timeline is to hide/show in the editor, it's not related to node visibility.
