### ISSUE TITLE
No error occurs when user creates a joint by selecting any kind of  joint and dragging a line between the circles in the properties pannel and the same sprites in the timeline

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#764]
1. Launch the Sprite Builder 1.2.
2. Tap file and create a new project.
3. In that new project create a layer Bear.ccb
4. Drag a physics node under the ccnode in the timeline.
5. Drag bearnoarms.png and beararm.png sprites under the physics node.
6. Now add any kind of joint in between them.
7. Now drag the line of Body A of joint from properties panel to the beararm.png and Body B again to the beararm.png
   
   -- Expected Result: Error should be produced that both the joint points can't be pointing to the same sprite.
   
   -- Result: No error occurs when both the joint point are set to the same sprites. 

The videos for the behaviors are given here:
Unusual behavior 
https://drive.google.com/file/d/0B23s5OMd3iivUnhuMGgtZ2dodmM/edit?usp=sharing
Normal behavior 
https://drive.google.com/file/d/0B23s5OMd3iivT08xbHJCZzlONXM/edit?usp=sharing

Mac OS X : 10.9.0
Xcode version: 5.0
Build: SpriteBuilder-1.2.0-beta.2

**Comment by khanbhai89** [comment]
This issue is still occurring on SpriteBuilderAdHoc-sb-1.3.0-rc.1-d49d1950d11b5a27d61b6234761197522d03875a_d6d92a9f14495012

Mac OS X: 10.9.5
XCode: 6.0

**Comment by Kanoot** [comment]
This issue is reoccurring.

Build: SpriteBuilder-1.3.5-rc.2

MAC OS: 10.9.5
XCode: 6.0

**Comment by khanbhai89** [comment]
This issue is still occurring on SpriteBuilder-1.3.6.rc.1.

Mac OS X: 10.9.5.
XCode: 6.0.

**Comment by sana20** [comment]
This issue is fixed on SB Version: 1.4.0-beta.02
Mac OS X: 10.10.1.
XCode: 6.0.

**Comment by khanbhai89** [comment]
This issue is still occurring on SpriteBuilder-1.4.0-rc.0.zip

Mac OS X:10.9.5
XCode: 6.0.

**Comment by sana20** [comment]
This issue is fixed on SpriteBuilder-1.4.8-rc.0 with SBAndroid Indie (SBAndroidPluginIndie-sbandroid-indie-704bb7c4b3507f7e).

Mac OS X: 10.10.1
XCode: 6.1.
Device: Note 2/4.1.1.

**Comment by Shahidwerplay** [comment]
This issue is still occurring on SpriteBuilder-1.4.9

Mac OS X:10.10.0
XCode: 6.2.
